version: '3.8'

services:

  localstack:
    healthcheck:
      test: "bash -c 'AWS_ACCESS_KEY_ID=fake AWS_SECRET_ACCESS_KEY=fake aws --endpoint-url=http://localhost:4566 s3 ls'"
      start_period: 1m
      timeout: 30s
      retries: 3
    image: localstack/localstack:0.14.3
    ports:
      - 4566:4566
    networks:
      hocs-network:
        aliases:
          - localhost.localstack.cloud
    environment:
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: eu-west-2
      SERVICES: sqs, sns
      SQS_PROVIDER: "elasticmq"
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d

networks:
  hocs-network:
