version: '3.8'

services:

  localstack:
    image: localstack/localstack:0.14.3
    ports:
      - 4566:4566
    networks:
      hocs-network:
        aliases:
          - localhost.localstack.cloud
    environment:
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: eu-west-2
      SERVICES: sqs, sns
      SQS_PROVIDER: "elasticmq"
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d

networks:
  hocs-network:
