info:
    app:
        fullname: Hocs Notify Service
        name: ${name:hocs-notify-service}
        version: ${version:0.0.1}

server:
    port: 8082
    shutdown: graceful

spring:
    main:
        banner-mode: off

management:
    endpoints:
        enabled-by-default: false
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true

aws:
    account:
        id: 123456789012
    queue:
        audit:
            name: notify-queue
    sqs:
        access:
            key: 12345
        region: eu-west-2
        secret:
            key: 12345

hocs:
    info-service: http://localhost:8085
    url: http://localhost:8080

notify:
    apiKey: aaaaaaaaaa-11111111-1111-1111-1111-111111111111-11111111-1111-1111-aaaa-aaaaaaaaaaaa
