apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hocs-notify
  name: hocs-notify
spec:
  maxReplicas: {{.MAX_REPLICAS}}
  minReplicas: {{.MIN_REPLICAS}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hocs-notify
  targetCPUUtilizationPercentage: 24
